### ISSUE TITLE
Typos in Instructions

### ISSUE THREAD

**Issue by DeweyVT03** [ppamidimarri/TeslaDashcamWeb#3]
Hi! Thanks for your contribution! I'm adding it to my Pi now as I am working to fix the Sentry file issue too. Hope it all works out.... Anyway, as I was going through your instructions, I noticed a couple errors/typos.

1.) in your configure nginx section, step 2 has a typo in filename. You have nginx.confg when it should be nginx.conf

2.) in your instructions to update sudoers, that step was a tad confusing... I think you are saying we need to create an entry for www-data, so do this command:
echo "www-data ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/020_www-data-nopasswd

3.) I had an issue with the rc.local script and the RClone config file. I don't know if my setup is unique or if I had an old version of their code- but I didn't have any file located at /root/.config/rclone/rclone.conf and my rclone settings had vanished. So I redid the "rclone config" steps again and it made the file at /root/.rclone.conf
So I moved that file to the /mutable/ drive and made a symbolic link. Then updated your rc.local copy line to 
/bin/cp /root/.rclone.conf /tmp/rclone.conf >> "$LOGFILE" 2>&1

**Comment by ppamidimarri** [comment]
@DeweyVT03 Thanks, i fixed these now.

**Comment by barjohn** [comment]
Your changes from @DeweyVT03 helped but I ran into new problems trying to build this using the new steps.  At the end of the step before Configure clone, I get the nginx welcome page.  Then I have problems with the rclone configuration section because it appears that none of the preceding gets loaded it on the raspi so I go to cimryan's instructions and load rclone using his instructions and stop before his exports as you don't show those in your instructions.  I'm not sure that is the right way to do it.  I then do the update sudoers and rc.local and then load your web site scripts.  On occasion if I am running as pi the change owners commands say I don't have permission and I have to use sudo to be root to execute them.  In any case afterwards I cannot get to the nginx web page.  It is either blank or I get one of the http error messages.  Finally, if you could clarify whose REPO and BRANCH to use to create the drives with to work on 8.x that would be great.  I really like this approach.  Thanks for your efforts.

**Comment by barjohn** [comment]
I forgot to ask, how do you get to the web page from the browser in your Tesla?
